/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DrShinRouteImport } from './routes/dr-shin'
import { Route as DrYongShinRouteImport } from './routes/dr-yong-shin'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as MeetTheTeamRouteImport } from './routes/meet-the-team'
import { Route as NewPatientsRouteImport } from './routes/new-patients'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DrShinRoute = DrShinRouteImport.update({
  id: '/dr-shin',
  path: '/dr-shin',
  getParentRoute: () => rootRouteImport,
} as any)
const DrYongShinRoute = DrYongShinRouteImport.update({
  id: '/dr-yong-shin',
  path: '/dr-yong-shin',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetTheTeamRoute = MeetTheTeamRouteImport.update({
  id: '/meet-the-team',
  path: '/meet-the-team',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPatientsRoute = NewPatientsRouteImport.update({
  id: '/new-patients',
  path: '/new-patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dr-shin': typeof DrShinRoute
  '/dr-yong-shin': typeof DrYongShinRoute
  '/insurance': typeof InsuranceRoute
  '/licenses': typeof LicensesRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/new-patients': typeof NewPatientsRoute
  '/patients': typeof PatientsRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dr-shin': typeof DrShinRoute
  '/dr-yong-shin': typeof DrYongShinRoute
  '/insurance': typeof InsuranceRoute
  '/licenses': typeof LicensesRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/new-patients': typeof NewPatientsRoute
  '/patients': typeof PatientsRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dr-shin': typeof DrShinRoute
  '/dr-yong-shin': typeof DrYongShinRoute
  '/insurance': typeof InsuranceRoute
  '/licenses': typeof LicensesRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/new-patients': typeof NewPatientsRoute
  '/patients': typeof PatientsRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/dr-shin'
    | '/dr-yong-shin'
    | '/insurance'
    | '/licenses'
    | '/meet-the-team'
    | '/new-patients'
    | '/patients'
    | '/privacy'
    | '/refunds'
    | '/services'
    | '/team'
    | '/terms'
    | '/unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/dr-shin'
    | '/dr-yong-shin'
    | '/insurance'
    | '/licenses'
    | '/meet-the-team'
    | '/new-patients'
    | '/patients'
    | '/privacy'
    | '/refunds'
    | '/services'
    | '/team'
    | '/terms'
    | '/unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/dr-shin'
    | '/dr-yong-shin'
    | '/insurance'
    | '/licenses'
    | '/meet-the-team'
    | '/new-patients'
    | '/patients'
    | '/privacy'
    | '/refunds'
    | '/services'
    | '/team'
    | '/terms'
    | '/unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DrShinRoute: typeof DrShinRoute
  DrYongShinRoute: typeof DrYongShinRoute
  InsuranceRoute: typeof InsuranceRoute
  LicensesRoute: typeof LicensesRoute
  MeetTheTeamRoute: typeof MeetTheTeamRoute
  NewPatientsRoute: typeof NewPatientsRoute
  PatientsRoute: typeof PatientsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dr-shin': {
      id: '/dr-shin'
      path: '/dr-shin'
      fullPath: '/dr-shin'
      preLoaderRoute: typeof DrShinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dr-yong-shin': {
      id: '/dr-yong-shin'
      path: '/dr-yong-shin'
      fullPath: '/dr-yong-shin'
      preLoaderRoute: typeof DrYongShinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-the-team': {
      id: '/meet-the-team'
      path: '/meet-the-team'
      fullPath: '/meet-the-team'
      preLoaderRoute: typeof MeetTheTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-patients': {
      id: '/new-patients'
      path: '/new-patients'
      fullPath: '/new-patients'
      preLoaderRoute: typeof NewPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DrShinRoute: DrShinRoute,
  DrYongShinRoute: DrYongShinRoute,
  InsuranceRoute: InsuranceRoute,
  LicensesRoute: LicensesRoute,
  MeetTheTeamRoute: MeetTheTeamRoute,
  NewPatientsRoute: NewPatientsRoute,
  PatientsRoute: PatientsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
